env:
  browser: true
  es2021: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - warn
    - never
  max-len:
    - warn
    - 120
  quotes:
    - off
  no-unused-vars:
    - error
    - vars: all
      args: none
