# Generated by Django 3.1 on 2021-02-02 12:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(help_text='Например: Мир Окон.', max_length=60, unique=True, verbose_name='Название компании')),
                ('legal_name', models.CharField(blank=True, help_text='Например: ООО Победа, ЗАО Лотос, ИП Кузнецов Иван Андреевич.', max_length=60, verbose_name='Наименование юрлица или ИП')),
                ('OGRN', models.CharField(blank=True, help_text='Введите 13 цифр, без пробелов.', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Неверный ОГРН')], verbose_name='ОГРН')),
                ('INN', models.CharField(blank=True, help_text='Введите 10 или 12 цифр, без пробелов.', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{12})$', 'Неверный ИНН')], verbose_name='ИНН')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка на ваш вебсайт')),
                ('email', models.EmailField(blank=True, help_text='Если вы оставите свой Email, мы сможем уведомить вас в случае возникновения неполадок с вашей учетной записью.', max_length=100, verbose_name='Контактный E-mail')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('datetime_changed', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Офис'), ('W', 'Склад')], max_length=1, verbose_name='Тип')),
                ('street_address', models.TextField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(70)], verbose_name='Городской адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='cities.city', verbose_name='Город')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(help_text='Телефон, по которому покупатели смогут с вами связаться.', max_length=128, region=None, verbose_name='Номер')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', related_query_name='phone', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
