# Generated by Django 3.1 on 2021-02-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='place',
            field=models.ForeignKey(help_text='Адрес, по которому можно самостоятельно забрать окно, после покупки.', on_delete=django.db.models.deletion.PROTECT, related_name='windows', related_query_name='window', to='sellers.place', verbose_name='Место покупки'),
        ),
        migrations.AddField(
            model_name='window',
            name='seller',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='windows', related_query_name='window', to='sellers.seller', verbose_name='Продавец'),
        ),
        migrations.AddIndex(
            model_name='window',
            index=models.Index(fields=['width'], name='catalog_win_width_6924e5_idx'),
        ),
        migrations.AddIndex(
            model_name='window',
            index=models.Index(fields=['height'], name='catalog_win_height_ae9352_idx'),
        ),
        migrations.AddIndex(
            model_name='window',
            index=models.Index(fields=['type'], name='catalog_win_type_e7ca1b_idx'),
        ),
    ]
